SanketKogekar

medium

# Loss of funds in case user decides to claim rewards in his safe contract.

## Summary
The `_to` in both claimETHPrize & claimERC20Prize functions is not marked to be `payable`. This could cause serious problem if user wants to claim funds in his safe contract.

## Vulnerability Detail
In `claimETHPrize` is would be recommended that `_to` variable is a `payable`
```solidity
 function claimETHPrize(
        address _to,
        uint256 _amount,
        bytes32[] calldata _proof
    ) external whenNotPaused nonReentrant {
```

## Impact
The transaction would always revert even though user has earned sufficient prizes or user might lost the prizes.

## Code Snippet
https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumPrizeDistributor.sol#L144

## Tool used

Manual Review

## Recommendation
Mark `_to` address as `payable`
